name: heart-disease-mlproject
channels:
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - pip:
    - mlflow==2.19.0
    - scikit-learn==1.8.0
    - pandas==2.3.3
    - numpy==2.4.4
    - matplotlib==3.10.9
    - python-dotenv==1.0.1
