name: CI - MLflow Training

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install Dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn pandas numpy matplotlib python-dotenv ucimlrepo

      - name: Generate Preprocessed Dataset
        run: |
          cd experimentation/preprocessing
          python automate.py
          cp heart_disease_preprocessing_train.csv ../../workflow-ci/MLProject/
          cp heart_disease_preprocessing_test.csv ../../workflow-ci/MLProject/

      - name: Run MLflow Project
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: |
          mlflow run workflow-ci/MLProject --env-manager=local

      - name: Upload Artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: |
            mlruns/
            confusion_matrix.png
            feature_importance.csv

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download Model Artifact
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: |
          RUN_ID=$(cat workflow-ci/MLProject/run_id.txt)
          mlflow artifacts download \
            --run-id $RUN_ID \
            --artifact-path model \
            --dst-path workflow-ci/MLProject/model

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/heart-disease-mlops:latest workflow-ci/MLProject/
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/heart-disease-mlops:latest
